server:
  port: 8090

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      orchestrator: orchestrator
      adress-validation-success: adress-validation-success
      adress-validation-fail: adress-validation-fail
    consumer:
      group-id: adress-validation-group
      auto-offset-reset: latest

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:adress}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      apache:
        kafka: OFF

graphql:
  uri: ${GRAPHQL_URI:http://localhost:8088/}